// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-patients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patients_default = defineTool({
  name: "list_patients",
  title: "List patients",
  description: "List patients in the Smart Health Card system. Supports optional search by name or phone number and a result limit.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive fragment matching full_name or phone_number."),
    limit: z.number().int().optional().describe("Max number of records to return (default 25, capped at 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("patients").select("id, full_name, phone_number, date_of_birth, gender, blood_group, created_at").order("created_at", { ascending: false }).limit(capped);
    if (search && search.trim()) {
      const s = search.trim().replace(/[%,]/g, "");
      query = query.or(`full_name.ilike.%${s}%,phone_number.ilike.%${s}%`);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-patient.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_patient_default = defineTool2({
  name: "get_patient",
  title: "Get patient details",
  description: "Fetch the full record for one patient by health card ID (UUID) or by phone number.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Patient UUID (health card ID)."),
    phone_number: z2.string().optional().describe("10-digit Indian mobile number of the patient.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, phone_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !phone_number) {
      return {
        content: [{ type: "text", text: "Provide either id or phone_number." }],
        isError: true
      };
    }
    const client = supabaseForUser2(ctx);
    let query = client.from("patients").select("*").limit(1);
    if (id) query = query.eq("id", id);
    else query = query.eq("phone_number", phone_number.replace(/\D/g, ""));
    const { data, error } = await query.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "No matching patient found." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { patient: data }
    };
  }
});

// src/lib/mcp/tools/register-patient.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var register_patient_default = defineTool3({
  name: "register_patient",
  title: "Register a new patient",
  description: "Create a new patient record with basic demographic, medical and emergency contact details.",
  inputSchema: {
    full_name: z3.string().describe("Patient's full name."),
    date_of_birth: z3.string().describe("Date of birth in YYYY-MM-DD format."),
    phone_number: z3.string().describe("10-digit Indian mobile number."),
    gender: z3.enum(["male", "female", "other"]),
    emergency_contact: z3.string().describe("10-digit emergency contact number."),
    blood_group: z3.enum(["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]).optional(),
    height: z3.string().optional().describe("Height in cm as a string."),
    weight: z3.string().optional().describe("Weight in kg as a string."),
    allergies: z3.array(z3.string()).optional(),
    chronic_conditions: z3.array(z3.string()).optional(),
    insurance_provider: z3.string().optional(),
    policy_number: z3.string().optional(),
    tpa_contact: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      full_name: input.full_name.trim(),
      date_of_birth: input.date_of_birth,
      phone_number: input.phone_number.replace(/\D/g, ""),
      gender: input.gender,
      emergency_contact: input.emergency_contact.replace(/\D/g, ""),
      blood_group: input.blood_group ?? null,
      height: input.height ?? null,
      weight: input.weight ?? null,
      allergies: input.allergies ?? [],
      chronic_conditions: input.chronic_conditions ?? [],
      insurance_provider: input.insurance_provider ?? null,
      policy_number: input.policy_number ?? null,
      tpa_contact: input.tpa_contact ?? null
    };
    const { data, error } = await supabaseForUser3(ctx).from("patients").insert(payload).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Patient registered. Health Card ID: ${data.id}`
        }
      ],
      structuredContent: { patient: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kfvpqejwnhqqwrswjkqj";
var mcp_default = defineMcp({
  name: "smart-health-card-mcp",
  title: "Smart Health Card",
  version: "0.1.0",
  instructions: "Tools for managing the Smart Health Card patient database. Use list_patients to browse or search, get_patient for a single record, and register_patient to create a new record.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_patients_default, get_patient_default, register_patient_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
